// Generated by Dagger (https://google.github.io/dagger).
package me.sankalpchauhan.learningdagger;

public final class DaggerCarComponent implements CarComponent {
  private DaggerCarComponent(Builder builder) {}

  public static Builder builder() {
    return new Builder();
  }

  public static CarComponent create() {
    return new Builder().build();
  }

  @Override
  public Car getCar() {
    return new Car(new Engine(), new Wheels());
  }

  public static final class Builder {
    private Builder() {}

    public CarComponent build() {
      return new DaggerCarComponent(this);
    }
  }
}
