// Generated by Dagger (https://google.github.io/dagger).
package me.sankalpchauhan.learningdagger;

import dagger.internal.Factory;

public final class Wheels_Factory implements Factory<Wheels> {
  private static final Wheels_Factory INSTANCE = new Wheels_Factory();

  @Override
  public Wheels get() {
    return provideInstance();
  }

  public static Wheels provideInstance() {
    return new Wheels();
  }

  public static Wheels_Factory create() {
    return INSTANCE;
  }

  public static Wheels newWheels() {
    return new Wheels();
  }
}
